"""A printed caption is either mapped to its key or recorded as withdrawn.

The Infosys documents print far more captions than the model consumes, and every
one of them has to be visible as a decision: mapped to a key that holds what the
caption says, or withdrawn with the reason on file. An unmapped caption reads as
an accident, and a caption the confidence engine parks on a key that states
something false about it is worse, because the wrong figure publishes under a
name that looks right.

Two families of decisions, made against the printed statements rather than the
names:

- Six captions have homes, and one memo beside them. "Payment of dividends" is the filing's own caption
  for the dividends line, read from the continuation page of both documents
  (printed 105 under 104, printed 111 under 110), and `canonical.cf.dividends_paid`
  was empty for this company because the aggregator's rows are refused by the
  statement guard. The four section totals and the printed bottom line are the
  statement's own skeleton: the sections sum to the bottom-line caption exactly
  in all three years (26,066 - 5,865 - 17,504 = 2,697 at FY24, and likewise at
  FY25 and FY26), which is the relationship the model derives the bottom line
  from, so the sections have to be the filing's totals and not whatever else the
  engine would suggest. The seventh is the filing's own exchange line, printed
  on the continuation page under the three sections ((84) / 82 / 1,600): the
  sections already sum to the bottom line without it, so it publishes as a
  memo outside them and the reconciliation check absorbs it.

- Thirty have none. The engine rates the first twenty-two low confidence
  (0.2, no key): their section totals are already mapped, and the balance-sheet
  cases cannot pick a key without replacing an aggregate with a component or
  putting two figures of one period under one identity. The next five the engine
  does suggest, at destinations that state something false: a pre-tax subtotal
  competing with the section total, a liability in an asset key, a deduction on
  the receipt line it adjusts, an ex-minority subtotal beside its own total, and
  a share-count note fragment on the liabilities-and-equity total. The last
  three the registry mapped itself, and each is a case where the cash flow
  statement's last-row rule lets page order publish a figure the filing does
  not support: the contingent line, beside the acquisition line it settles,
  overwrites the filing's (637) with its own (13); and the escrow pair, where
  deposits (1,815) and redemptions 1,815 net to zero for FY26 but the
  redemption prints last, so one side of a pair published as the year's line.
  Withdrawn is the recorded state for all thirty: no canonical datapoint, not
  counted as an unmapped gap, and a row in the review queue either way.
"""
from __future__ import annotations

from datetime import datetime

from backend.data.store import RawDatapoint
from backend.normalization.financials import mapper
from backend.normalization.taxonomy.registry import (
    RAW_METRIC_MAP,
    WITHDRAWN_LABELS,
)

# (caption, section, a figure the filing prints for it, the key it belongs on)
# for every caption this registry maps. The values are the printed ones so a
# leak would show a real number, not a placeholder integer nobody could place.
MAPPED_FIGURES = [
    (
        "Payment of dividends",
        "CASH FLOW",
        -18653.0,
        "canonical.cf.dividends_paid",
    ),
    (
        "Net cash generated by operating activities",
        "CASH FLOW",
        35824.0,
        "canonical.cf.operating_activities",
    ),
    (
        "Net cash generated/(used) in investing activities",
        "CASH FLOW",
        -5865.0,
        "canonical.cf.investing_activities",
    ),
    (
        "Net cash generated from investing activities",
        "CASH FLOW",
        108.0,
        "canonical.cf.investing_activities",
    ),
    (
        "Net cash used in financing activities",
        "CASH FLOW",
        -39786.0,
        "canonical.cf.financing_activities",
    ),
    (
        "Net increase/(decrease) in cash and cash equivalents",
        "CASH FLOW",
        -3854.0,
        "canonical.cf.net_change_in_cash",
    ),
    (
        "Effect of exchange rate changes on cash and cash equivalents",
        "CASH FLOW",
        1600.0,
        "canonical.cf.fx_effect",
    ),
]

# (caption, section, a figure the filing prints) for every caption withdrawn
# here. Same rule: the printed figure, so a leak is recognizable.
WITHDRAWN_FIGURES = [
    ("Deposits placed with corporation", "CASH FLOW", -944.0),
    ("Redemption of deposits placed with corporation", "CASH FLOW", 725.0),
    ("Expenditure on property, plant and equipment and intangibles", "CASH FLOW", -2201.0),
    (
        "Expenditure on property, plant and equipment and intangibles, "
        "net of sale proceeds (Refer",
        "CASH FLOW",
        -2727.0,
    ),
    (
        "Impairment loss recognized/(reversed) under expected credit loss model",
        "CASH FLOW",
        33.0,
    ),
    (
        "Exchange differences on translation of assets and liabilities, net",
        "CASH FLOW",
        954.0,
    ),
    ("Other receipts", "CASH FLOW", 15.0),
    ("Other payments", "CASH FLOW", -250.0),
    ("Loan repayment of in-tech Holding GmbH", "CASH FLOW", -985.0),
    (
        "Loan repayment of in-tech Holding GmbH (Refer to note 2.10)",
        "CASH FLOW",
        -985.0,
    ),
    (
        "Shares issued on exercise of employee stock options",
        "CASH FLOW",
        2.0,
    ),
    (
        "Payment of dividends to non-controlling interests of subsidiary",
        "CASH FLOW",
        -3.0,
    ),
    ("Payment towards purchase of non-controlling interest", "CASH FLOW", -2.0),
    ("Total comprehensive income", "PROFIT & LOSS", 32811.0),
    (
        "Total other comprehensive income/(loss), net of tax",
        "PROFIT & LOSS",
        3337.0,
    ),
    (
        "Equity instruments through other comprehensive income, net",
        "PROFIT & LOSS",
        397.0,
    ),
    ("Exchange differences on translation of foreign operations", "PROFIT & LOSS", 3256.0),
    ("Fair value changes on investments, net", "PROFIT & LOSS", -27.0),
    (
        "Remeasurement of the net defined benefit liability/asset, net",
        "PROFIT & LOSS",
        -288.0,
    ),
    ("Right-of-use assets", "BALANCE SHEET", 6177.0),
    ("Share premium", "BALANCE SHEET", 1839.0),
    ("Employee benefit obligations", "BALANCE SHEET", 3524.0),
    # The wrong-destination family: each the engine's own suggestion, refused.
    ("Cash generated from operations", "CASH FLOW", 44472.0),
    ("Deferred income tax liabilities", "BALANCE SHEET", 1679.0),
    ("Interest and dividend income", "CASH FLOW", -1125.0),
    (
        "Total equity attributable to equity holders of the Company",
        "BALANCE SHEET",
        92852.0,
    ),
    (
        "authorized, issued and outstanding 4,143,607,528 (4,139,950,635) equity",
        "BALANCE SHEET",
        2071.0,
    ),
    # And two the registry itself mapped, both where the cash flow statement's
    # last-row rule would publish a figure the filing does not support.
    (
        "Payment of contingent consideration pertaining to acquisition of business",
        "CASH FLOW",
        -13.0,
    ),
    (
        "Escrow and other deposits pertaining to Buyback",
        "CASH FLOW",
        -1815.0,
    ),
    (
        "Redemption of escrow and other deposits pertaining to Buyback",
        "CASH FLOW",
        1815.0,
    ),
]


def _raw(label: str, section: str, value: float) -> RawDatapoint:
    return RawDatapoint(
        id="figure-%s" % label[:6].replace(" ", ""),
        company_id="fixture_co",
        metric_raw=label,
        period_label="FY26",
        period_end_date=datetime(2026, 3, 31).date(),
        value=value,
        currency="INR",
        units="crores",
        source="nse_filing",
        source_location="fixture p.1",
        section=section,
        status="reported",
        update_date=datetime.now(),
    )


class TestTheCaptionsWithHomesReachThem:
    # Every map_raw_datapoints call in this file points the review queue at a
    # database of its own: runs used to write fixture_co rows into the shared
    # store, one set per test run.
    def test_each_reaches_its_key_with_the_printed_figure(self, tmp_path):
        for label, section, value, key in MAPPED_FIGURES:
            canonical, _mappings, unmapped = mapper.map_raw_datapoints(
                [_raw(label, section, value)], db_path=tmp_path / "queue.db"
            )
            keys = [c.canonical_key for c in canonical]
            assert keys == [key], (
                "%r reached %s; it belongs on %s, and the figure the filing "
                "prints under these exact words is %.0f" % (label, keys, key, value)
            )
            assert canonical[0].value == value, (
                "the figure moved on the way in: %r" % canonical[0].value
            )
            assert label not in unmapped, (
                "the caption is mapped by the registry but reported as a gap"
            )

    def test_each_is_registered_and_not_withdrawn(self):
        for label, _section, _value, _key in MAPPED_FIGURES:
            assert label in RAW_METRIC_MAP, (
                "the registry entry for %r is gone, so its key goes back to "
                "empty or to whatever the engine would suggest" % label
            )
            assert label not in WITHDRAWN_LABELS, (
                "%r cannot be both mapped and withdrawn; the registry lookup "
                "would succeed and the withdrawal would never be reached" % label
            )


class TestTheCaptionsWithoutAHomeAreRecorded:
    def test_every_one_of_them_is_a_withdrawn_label(self):
        missing = [
            label
            for label, _section, _value in WITHDRAWN_FIGURES
            if label not in WITHDRAWN_LABELS
        ]
        assert not missing, (
            "%r is not in WITHDRAWN_LABELS, so it reads as an unmapped accident "
            "rather than a recorded decision" % missing
        )
        assert len(WITHDRAWN_FIGURES) == 30, (
            "the family changed size (%d); add or remove the caption itself, not "
            "silently the count" % len(WITHDRAWN_FIGURES)
        )

    def test_none_of_them_is_also_in_the_registry(self):
        both = [
            label
            for label, _section, _value in WITHDRAWN_FIGURES
            if label in RAW_METRIC_MAP
        ]
        assert not both, (
            "%r is registered AND withdrawn, so the registry lookup wins and the "
            "withdrawal is inert" % both
        )

    def test_none_reaches_a_canonical_datapoint(self, tmp_path):
        for label, section, value in WITHDRAWN_FIGURES:
            canonical, _mappings, _unmapped = mapper.map_raw_datapoints(
                [_raw(label, section, value)], db_path=tmp_path / "queue.db"
            )
            leaked = [c for c in canonical if c.metric_raw == label]
            assert not leaked, (
                "%r reached canonical as %s = %.1f. Either no key holds this "
                "line honestly, or the only key that would take it states "
                "something false about what the figure is."
                % (
                    label,
                    ", ".join(sorted({c.canonical_key for c in leaked})),
                    leaked[0].value,
                )
            )

    def test_none_is_counted_as_an_unmapped_gap(self, tmp_path):
        """A recorded decision is not a coverage gap; the two states differ.

        An unmapped caption tells a reader something is missing. These are not
        missing -- they were looked at and deliberately kept out, and the review
        queue holds the name either way.
        """
        for label, section, value in WITHDRAWN_FIGURES:
            _canonical, _mappings, unmapped = mapper.map_raw_datapoints(
                [_raw(label, section, value)], db_path=tmp_path / "queue.db"
            )
            assert label not in unmapped, (
                "%r is reported unmapped, so the coverage count claims a gap that "
                "was already decided" % label
            )
