from __future__ import annotations

"""
SEC EDGAR structured data ingestion module.

Parses XBRL company facts and US GAAP filing concepts, returning
provenance-tagged RawDatapoint records for US-listed filers.

Design decision — single-source by design:
    India-sourced ingestion (screener.py) reconciles data from a primary
    export against a secondary BSE/NSE filing source. SEC EDGAR company facts
    are structured XBRL, machine-generated, and authoritative by definition.
    Reconciling EDGAR against a second source would risk double-counting
    adjustments and is intentionally omitted here. The Source literal
    "sec_edgar" identifies EDGAR-sourced records throughout the pipeline
    and should never trigger reconciliation code paths.

All values are in USD millions unless overridden at the parser call site.
"""

import hashlib
from datetime import date, datetime
from pathlib import Path

import openpyxl

from backend.data.store import RawDatapoint, Source, Status


def _datapoint_id(company_id: str, metric: str, period: str, source: str, section: str, row: int) -> str:
    return hashlib.sha1(f"{company_id}|{section}|{metric}|{period}|{source}|{row}".encode()).hexdigest()


def _clean(v) -> float | None:
    if v is None or v == "":
        return None
    if isinstance(v, float):
        return v
    s = str(v).replace(",", "").strip()
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def _period_label(d: date) -> str:
    return f"FY{str(d.year)[2:]}"


def parse_sec_edgar_export(path: str | Path, company_id: str = "aapl_us") -> list[RawDatapoint]:
    """Parse SEC EDGAR company facts structured export into RawDatapoints.

    Args:
        path: Path to the SEC EDGAR source XLSX file (generated by generate_us_sources.py).
        company_id: Dynamic company identifier supplied by the caller at ingestion time
            (e.g. "aapl_us", "msft_us", "infy_us"). Not a static constant.

    Returns:
        List of RawDatapoint records tagged with source="sec_edgar",
        currency="USD", units="millions". Reconciliation against a second
        source is intentionally omitted (see module docstring).
    """
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Data Sheet"]
    rows = list(ws.iter_rows(values_only=True))

    datapoints: list[RawDatapoint] = []
    header_idx = None
    for i, row in enumerate(rows):
        if row[0] in ("PROFIT & LOSS", "BALANCE SHEET", "CASH FLOW:"):
            header_idx = i
        if row[0] == "Report Date" and header_idx is not None:
            periods: list[date] = [r.date() for r in row[1:] if hasattr(r, "date")]
            section = rows[header_idx][0]
            for j in range(i + 1, len(rows)):
                label = (rows[j][0] or "").strip()
                if not label or (isinstance(rows[j][0], str) and rows[j][0] in ("PROFIT & LOSS", "BALANCE SHEET", "CASH FLOW:", "Quarters", "PRICE:", "DERIVED:")):
                    break
                values = [_clean(v) for v in rows[j][1:]]
                for k, (period, val) in enumerate(zip(periods, values)):
                    if val is None:
                        continue
                    source: Source = "sec_edgar"
                    status: Status = "reported"
                    offset = k + 2
                    col = openpyxl.utils.get_column_letter(offset + 1)
                    datapoints.append(
                        RawDatapoint(
                            id=_datapoint_id(company_id, label, _period_label(period), "sec_edgar", section, j + 1),
                            company_id=company_id,
                            metric_raw=label,
                            period_label=_period_label(period),
                            period_end_date=period,
                            value=val,
                            currency="USD",
                            units="millions",
                            source=source,
                            source_location=f"SEC_EDGAR_CompanyFacts!{col}{j + 1}",
                            status=status,
                            update_date=datetime.now(),
                        )
                    )
            header_idx = None
    wb.close()
    return datapoints
